export default {
  login: "weiiwu",
  id: 17314519,
  node_id: "MDQ6VXNlcjE3MzE0NTE5",
  avatar_url: "https://avatars1.githubusercontent.com/u/17314519?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/weiiwu",
  html_url: "https://github.com/weiiwu",
  followers_url: "https://api.github.com/users/weiiwu/followers",
  following_url: "https://api.github.com/users/weiiwu/following{/other_user}",
  gists_url: "https://api.github.com/users/weiiwu/gists{/gist_id}",
  starred_url: "https://api.github.com/users/weiiwu/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/weiiwu/subscriptions",
  organizations_url: "https://api.github.com/users/weiiwu/orgs",
  repos_url: "https://api.github.com/users/weiiwu/repos",
  events_url: "https://api.github.com/users/weiiwu/events{/privacy}",
  received_events_url: "https://api.github.com/users/weiiwu/received_events",
  type: "User",
  site_admin: false,
  name: "Will Wu",
  company: "Freelance",
  blog: "https://willwu.net/",
  location: "Brisbane",
  email: null,
  hireable: null,
  bio: "\r\n    I think (and eat), therefore I am a programmer....\r\n",
  twitter_username: "willwwu",
  public_repos: 16,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2016-02-18T11:50:20Z",
  updated_at: "2020-07-22T00:27:34Z",
};
